apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sandbox
      env: dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sandbox
        env: dashboard
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: region
                operator: In
                values:
                - spai
              - key: environment
                operator: In
                values:
                - stg
      imagePullSecrets:
      - name: dockerhub
      containers:
      - env:
        - name: DEBUG
          value: "false"
        image: mptrabalho/sandbox-dashboard:latest
        imagePullPolicy: Always
        name: flask
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
