apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sandbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: region
                operator: In
                values:
                - spai
              - key: environment
                operator: In
                values:
                - stg
      containers:
      - image: nginx:stable
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          limits:
            cpu: 150m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: vol-conf
          readOnly: true
          subPath: default.conf
      volumes:
      - configMap:
          defaultMode: 420
          name: default.conf
          optional: false
        name: vol-conf