apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox
spec:
  rules:
  - host: sandbox.k8s.mpt.mp.br
    http:
      paths:
      - backend:
          service:
            name: sandbox
            port:
              number: 80
        path: /
        pathType: Prefix
